services:
  - type: web
    name: videh-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FAST2SMS_API_KEY
        value: BfJKY5R0A6c2H7WiUQT3Lasm4V8NMIuzjyEqxgwGZnoCPtDdObyXb7puYJ09hW3FkBUmIrDM8wClfaNL
      - key: FAST2SMS_SENDER_ID
        value: VIDEHE
      - key: DLT_TEMPLATE_ID
        value: "1007181628875366114"
